development:
  sessions:
    default:
      database: pathfinder_development
      hosts:
        - localhost:27017
      options:
  options:
test:
  sessions:
    default:
      database: pathfinder_test
      hosts:
        - localhost:27017